export const BLACK_LIST_CHAT_WORDS = [
  '10M10m',
  '10 millones$10M',
  '$10m$10 millones',
  'Diez millones$10k',
  '$10 mil10k',
  '10 mil Sorteo',
  'ScammerScammers',
  'scammer',
  'scammers',
  'Mother fuckerMotherfucker',
  'Mother fuckersMotherfuckers',
  'Motherfucker',
  'mother fucker',
  'mother fuckers',
  'GordaGord4',
  'g0rd4',
  'gord4',
  'G0rd4G0rda',
  'puta',
  'Pvt4Put4',
  'pvt4',
  'put4',
  'pvta',
  'putilla',
  'pringao',
  'rickcoinestafa',
  '@rickestafa',
  'rickestafa',
  'Tokens quemados',
  'Tokens Burned',
  '10 millones de Rick',
  '10millones de Ricks',
  '10m de Rick',
  '10M de Ricks',
  '10 millones congelados',
  'puta mierda',
  'puta basura',
  'puta estafa',
  'verga',
  'v3rg4',
  'verg4',
  'v3rga',
  'cagada',
  'gay',
  'g4y',
  'maricon',
  'm4r1c0n',
  'maric0n',
  'm4ric0n',
];
