export const COMMANDS = {
  INFO: 'precio',
  LINK: 'links',
  RULES: 'reglas',
  HELP: 'faqs',
  SHOW_COMMANDS: 'comandos',
  BAN: 'ban',
  UNBAN: 'unban',
  MUTE: 'mute',
  UNMUTE: 'unmute',
  MUTE_ALL: 'muteall',
  UNMUTE_ALL: 'unmuteall',
  AUTOMATIC: 'alertas',
  CREATE_TO_EARN: 'createtoearn',
  BITGET: 'bitget',
};
